:bug: Fixing bug with repair allocation
0chain/zboxcli pull request #135
Opened 2021-11-30 13:59 UTC by moldis

2021-11-30 16:46 UTC, stewartie4 commented on cmd/delete.go
> +			println("DEVELOPER ONLY. Make sure you understand meaning of blobber_url")
should this be removed from the customer facing CLI?

2021-11-30 16:47 UTC, stewartie4 commented on cmd/delete.go
> +	deleteCmd.Flags().String("blobber_url", "", "DEVELOPER ONLY, set it if you want delete file from specific blobber")
this can't be merged as part of the customer facing CLI

2021-11-30 16:48 UTC, stewartie4 commented
What's the high level purpose of this PR?

2021-12-10 08:47 UTC, moldis commented on cmd/delete.go
> +			println("DEVELOPER ONLY. Make sure you understand meaning of blobber_url")
@stewartie4 I need this for system_tests to emulate broken files hashes in blobbers

2021-12-10 11:42 UTC, stewartie4 commented on cmd/delete.go
> +			println("DEVELOPER ONLY. Make sure you understand meaning of blobber_url")
we shouldn't be modifying the public CLI for testing purposes 
You can call the blobber REST API directly in system tests to break files on individual blobbers

2022-02-12 20:50 UTC, vincenzopalazzo approved these changes
LGTM

2022-02-12 23:37 UTC, stewartie4 commented
How do these affect repair system tests @moldis ?

2022-02-14 00:17 UTC, stewartie4 requested changes
Remove the developer flags from the user facing CLI
Unless we intend that customers be able to do this?
https://github.com/0chain/zboxcli/pull/135/files#r766613602

2022-06-17 02:32 UTC, closed without merging