added feed and live command with upload.
0chain/zboxcli pull request #162
Opened 2022-02-08 03:54 UTC by princeparmar

added feed and live command
feed = upload --sync (live upload of remote file)
live = upload --live (live upload of local file)
Signed-off-by: Pradip Parmar <pradip@alfa-creator.com>

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
...

2022-02-08 23:01 UTC, cnlangzi requested changes
please update README.md too

2022-02-08 23:01 UTC, cnlangzi commented on cmd/upload.go
> +	Short: "live upload from remote device",
please check https://github.com/0chain/zboxcli#upload , update description.

2022-02-12 15:23 UTC, cnlangzi requested changes

2022-02-12 15:23 UTC, cnlangzi commented on README.md
> +Use `feed` command to automatically download segment files from remove live feed with `--downloader-args "-f 22"`
```suggestion
Use `feed` command to automatically download segment files from remote live feed with `--downloader-args "-q -f best"`
```

2022-02-12 15:23 UTC, cnlangzi commented on README.md
> +| localpath               | yes      | local path of the file to upload                                   |         | file path              |
```suggestion
| localpath               | yes      | local path of segment files to download, generate and upload                                   |         | file path              |
```

2022-02-12 15:23 UTC, cnlangzi commented on README.md
> +| localpath               | yes      | local path of the file to upload                                   |         | file path              |
```suggestion
| localpath               | yes      | local path of segment files to download, generate and upload                                   |         | file path              |
```

2022-02-12 15:23 UTC, cnlangzi commented on cmd/upload.go
> +	Short: "live upload from remote device",
```suggestion
	Short: "download segment files from remote live feed, and upload",
```

2022-02-12 15:23 UTC, cnlangzi commented on cmd/upload.go
> +	Long:  `live upload from remote device`,
```suggestion
	Long: "download segment files from remote live feed, and upload",
```

2022-02-12 15:23 UTC, cnlangzi commented on cmd/upload.go
> +	Short: "live upload from local device",
```suggestion
	Short: "capture video and audio streaming form local devices, and upload",
```

2022-02-12 15:23 UTC, cnlangzi commented on cmd/upload.go
> +	Long:  `live upload from local device`,
```suggestion
	Long: "capture video and audio streaming form local devices, and upload",
```

2022-02-12 20:48 UTC, vincenzopalazzo approved these changes
LGTM, just a couple of stylistic comment that you can ignore

2022-02-12 20:48 UTC, vincenzopalazzo commented on cmd/upload.go
> +		}
```suggestion
		if err := startChunkedUpload(cmd, allocationObj, localpath, thumbnailpath, remotepath, encrypt, chunkSize, attrs, statusBar, false); err != nil {
			PrintError("Upload failed.", err)
			os.Exit(1)
		}
```

2022-02-12 20:48 UTC, vincenzopalazzo commented on cmd/upload.go
> +		chunkSize, _ := cmd.Flags().GetInt("chunksize")
```suggestion
		chunkSize, err := cmd.Flags().GetInt("chunksize")
		if err != nil {
		  log.Debug(err)
		}
```

More information are always better

2022-02-12 20:48 UTC, vincenzopalazzo commented on cmd/upload.go
> +			)
```suggestion
	var wp common.WhoPays
	var wps string
```

IMO this is an antipattern in Go lang

2022-02-13 09:37 UTC, cnlangzi approved these changes

2022-02-13 09:37 UTC, cnlangzi requested changes
please remove `--live` and `--sync` tags from `upload` command. and update README.md, system_test and 0proxy. thanks.

2022-02-14 02:40 UTC, cnlangzi approved these changes

2022-02-14 03:15 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/156-live-feed-command  |
| gosdk  | staging  |
| zboxcli  | feature/156-live-feed-command  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-15 07:58 UTC, merged