pay rewards
0chain/zboxcli pull request #163
Opened 2022-02-08 10:26 UTC by Sriep

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
...
Add pay_rewards command to pay stake pool rewards. Needs https://github.com/0chain/0chain/pull/967 and https://github.com/0chain/gosdk/pull/368

2022-02-09 17:39 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | sp_gosdk_rewards  |
| zboxcli  | sp_reward  |
| zwalletcli  | staging  |
| 0chain  | sp-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-10 18:03 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | sp_gosdk_rewards  |
| zboxcli  | sp_reward  |
| zwalletcli  | staging  |
| 0chain  | sp-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-13 03:54 UTC, peterlimg requested changes

2022-02-13 03:54 UTC, peterlimg commented on cmd/collect_reward.go
> +	ProviderAuthorizer
We can use the Provider defined in sdk so that we don't have to maintain duplicate Providers everywhere it needs.

2022-02-13 03:54 UTC, peterlimg commented on cmd/collect_reward.go
> +			_, err = sdk.CollectRewards(poolId, int(ProviderBlobber))
Use Provider defined in sdk

2022-02-13 03:54 UTC, peterlimg commented on test.txt
> +The quick brown fox jumped over the lazy dog.
Seems like an unexpected file committed.

2022-02-15 04:41 UTC, peterlimg approved these changes
LGTM

2022-02-19 17:09 UTC, merged