Update allocation add/remove blobber
0chain/zboxcli pull request #189
Opened 2022-03-08 14:03 UTC by Sriep

A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

2022-03-31 11:43 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | update-ba  |
| zboxcli  | update-ba  |
| zwalletcli  | staging  |
| 0chain  | update-blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-03 09:42 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | update-ba  |
| zboxcli  | update-ba  |
| zwalletcli  | staging  |
| 0chain  | update-blobbers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-04 00:27 UTC, peterlimg requested changes

2022-04-04 00:27 UTC, peterlimg commented on cmd/updateallocation.go
> +		if flags.Changed("add_blobber") == true {
Could be `if flags.Changed("add_blobber") {`

2022-04-04 00:27 UTC, peterlimg commented on cmd/updateallocation.go
> +			if flags.Changed("remove_blobber") == true {
Same as "add_blobber"

2022-04-05 10:27 UTC, peterlimg approved these changes
lgtm

2022-04-05 15:01 UTC, merged