fix(wasm): fixed time.Sleep and Sign issues on wasm
0chain/zboxcli pull request #190
Opened 2022-03-11 02:25 UTC by cnlangzi

A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

2022-03-11 03:37 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/time_sleep_wasm  |
| zboxcli  | fix/time_sleep_wasm  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-11 05:25 UTC, peterlimg requested changes

2022-03-11 05:25 UTC, peterlimg commented on cmd/walletinfo.go
> +		sign, err := sys.Sign(data, client.GetClient().SignatureScheme, client.GetClientSysKeys())
We don't need this change if the gosdk defined the client.Sign function as I suggested

2022-03-12 22:35 UTC, peterlimg approved these changes
lgtm

2022-03-13 06:38 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/time_sleep_wasm  |
| zboxcli  | fix/time_sleep_wasm  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-13 07:30 UTC, merged