Fix/download cost calculation
0chain/zboxcli pull request #198
Opened 2022-03-23 09:10 UTC by lpoli

This PR solves download cost calculation of `zbox get-download-cost` and `zbox get` commands

2022-03-23 13:29 UTC, peterlimg requested changes

2022-03-23 13:29 UTC, peterlimg commented on cmd/getallocation.go
> +		blockspermarker, err := cmd.Flags().GetInt("blockspermarker")
variable `blockspermarker` -> `blocksPerMarker`

The flag `blockspermarker` -> `blocks-per-marker` if it is a new flag.

2022-03-23 13:29 UTC, peterlimg commented on cmd/getallocation.go
> +func calculateDownloadCost(alloc *sdk.Allocation, fileSize int64, blockspermarker int) common.Balance {
blockspermarker -> blocksPerMarker

2022-03-23 13:29 UTC, peterlimg commented on cmd/getallocation.go
> +	getallocationCmd.PersistentFlags().Int("blockspermarker", 10, "blocks signed per Read Marker")
blockspermarker -> blocks-per-marker

2022-03-23 13:29 UTC, peterlimg commented on cmd/getallocation.go
> +	singleShardSize := fileref.CHUNK_SIZE * dataShards
Shouldn't we include the ParityShards?

2022-03-23 16:06 UTC, lpoli commented on cmd/getallocation.go
> +	singleShardSize := fileref.CHUNK_SIZE * dataShards
No we should not. Because data is divided equally within data-shards regardless of number of parity shards

2022-03-23 16:08 UTC, lpoli commented on cmd/getallocation.go
> +		blockspermarker, err := cmd.Flags().GetInt("blockspermarker")
@peterlimg Its a new flag for this command but there is `download` command that uses `blockspermarker`. This flag can be used in other tools so to make it consistent with `download`, I followed same pattern

2022-03-23 22:50 UTC, peterlimg requested changes, later dismissed

2022-03-23 22:50 UTC, peterlimg commented on cmd/getallocation.go
> +		blocksPerMarker, err := cmd.Flags().GetInt("blocksPerMarker")
The flag is `blocks-per-maker`

2022-03-27 18:50 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/download-cost-calculation  |
| gosdk  | staging  |
| zboxcli  | fix/download-cost-calculation  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-27 18:54 UTC, Kishan-Dhakan approved these changes
Approving as @lpoli asked to merge this branch here: https://0chain.slack.com/archives/C02AV6MKT36/p1648395601349229?thread_ts=1648394208.517439&cid=C02AV6MKT36 and this is blocking other Devs.

2022-03-27 18:54 UTC, merged