S3 migration command to migrate data from S3 to dStorage
0chain/zboxcli pull request #21
Opened 2021-05-14 00:34 UTC by iamrz1

2021-05-19 08:28 UTC, guruhubb commented
@iamrz1 do you have an updated readme and cli help for this? Please also do a UML flow of the architecture and detailed documentation

2021-05-19 13:54 UTC, iamrz1 commented
> @iamrz1 do you have an updated readme and cli help for this? Please also do a UML flow of the architecture and detailed documentation

Sure, on it.

2021-05-24 09:43 UTC, sculptex commented
how do i build this to test? starting from scratch. I tried to pull then pull this branch but build number is same

2021-05-25 13:06 UTC, iamrz1 commented
> how do i build this to test? starting from scratch. I tried to pull then pull this branch but build number is same

Use the `streaming-upload` branch of go-sdk in go.mod file, then run `go mod tidy && go mod vendor` as usual. build binary with `make install`. Look up `S3 migration` in doc to migrate data from s3. It should work as expected.

2021-05-25 14:09 UTC, sculptex commented
> > how do i build this to test? starting from scratch. I tried to pull then pull this branch but build number is same
> 
> Use the `streaming-upload` branch of go-sdk in go.mod file, then run `go mod tidy && go mod vendor` as usual. build binary with `make install`. Look up `S3 migration` in doc to migrate data from s3. It should work as expected.

okay, I think I built it,
./zbox version
Version info:
	zbox....:  v1.0.1-188-g2fc6997-dirty
	gosdk...:  v1.2.2


what docs are you referring to?

2021-05-25 14:48 UTC, iamrz1 commented
> okay, I think I built it

Great!

> what docs are you referring to?

Just the readme file in this PR

2021-05-26 18:39 UTC, sculptex commented
okay I found in in the readme, unfortunately the hyperlink from the commands in the branch readme is hard coded to base zboxcli so it doesn't work.
Now that command is not in the zbox I built, I tried several methods including pulling that branch of gosdk and referencing it locally, none of them have that command.
There needs to be a reproduceable method for non-git-experts such as myself

2021-06-12 22:39 UTC, stewartie4 requested changes
There seems to be missing unit test coverage

2021-06-12 22:39 UTC, stewartie4 commented on cmd/s3-migration.go
> +package cmd
Add unit tests for this file

2021-06-12 22:39 UTC, stewartie4 commented on config/migration.go
> +package config
Add unit tests

2021-06-12 22:39 UTC, stewartie4 commented on config/s3.go
> +package config
Add unit tests

2021-06-12 22:39 UTC, stewartie4 commented on service/status_bar.go
> +package service
Add unit tests

2021-07-23 10:28 UTC, Sriep commented
Market place PRs https://github.com/0chain/gosdk/pull/34 and https://github.com/0chain/zboxcli/pull/23 have been merged, so recheck auth ticket use. Remove commented-out code and resolve todos and merge conflicts.

2022-02-15 02:59 UTC, cnlangzi commented
@lpoli  should we close this PR?

2022-06-12 16:18 UTC, closed without merging