Fix/revert to readcounter
0chain/zboxcli pull request #211
Opened 2022-04-11 11:47 UTC by lpoli

###Changes
This PR reverts Readmarker changes from read size to read counter

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

2022-04-12 12:34 UTC, peterlimg requested changes

2022-04-12 12:34 UTC, peterlimg commented on go.mod
> +replace github.com/0chain/gosdk => ../gosdk
This go mod replace should not be committed

2022-04-13 13:53 UTC, peterlimg approved these changes
lgtm

2022-04-18 16:52 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/revert-to-readcounter  |
| zwalletcli  | staging  |
| 0chain  | fix/revert-to-readcounter  |
| blobber  | fix/revert-to-readcounter  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-21 10:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/revert-to-readcounter  |
| zboxcli  | fix/revert-to-readcounter  |
| zwalletcli  | staging  |
| 0chain  | fix/revert-to-readcounter  |
| blobber  | fix/revert-to-readcounter  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-22 11:56 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/revert-to-readcounter  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/revert-to-readcounter  |
| zwalletcli  | staging  |
| 0chain  | fix/revert-to-readcounter  |
| blobber  | fix/revert-to-readcounter  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-23 06:58 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/revert-to-readcounter  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/revert-to-readcounter  |
| zwalletcli  | staging  |
| 0chain  | fix/revert-to-readcounter  |
| blobber  | fix/revert-to-readcounter  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-23 15:16 UTC, merged