Added StreamUpload
0chain/zboxcli pull request #26
Opened 2021-06-02 07:37 UTC by cnlangzi

link to 0chain/blobber#166

add parameters on ./zbox upload

- stream: true/false.  false is default
- chunksize: int.  64KB is default

2021-06-11 14:08 UTC, cnlangzi commented
it works with partial stream because of `Avoids outsourcing attach` with merkle tree now.
- update with stream mode
- hash is still ask data is fully loaded in memory for hashing

I would suggest to review PR, and get it passed first. Because there are too much changes now.  Let us follow it on https://github.com/0chain/zboxcli/issues/36

2021-06-11 15:44 UTC, cnlangzi commented
@Sriep please help me to review PR if you get some time left , thanks.

2021-06-11 16:21 UTC, Sriep requested changes

2021-06-11 16:21 UTC, Sriep commented on cmd/root.go
> +var devserver bool
Camel case `devServer`.

2021-06-11 16:21 UTC, Sriep commented on cmd/upload.go
> +				goto ThrownErr
Please don't use `goto. Find another way. 
For instance you could add the `ThrowErr`code to a `defer`  block and replace the  `goto ThrowErr`  with  `return`.

2021-06-14 23:06 UTC, cnlangzi commented
ignore it first. thanks.

2021-06-14 23:06 UTC, closed without merging