Feature/list recent files
0chain/zboxcli pull request #284
Opened 2022-08-09 13:30 UTC by lpoli

This PR contains command that lists recently added refs.

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber: https://github.com/0chain/blobber/pull/755
- gosdk: https://github.com/0chain/gosdk/pull/532
- system_test: https://github.com/0chain/system_test/pull/369
- zwalletcli:
- Other: ...

2022-08-10 04:45 UTC, peterlimg requested changes

2022-08-10 04:45 UTC, peterlimg commented on cmd/fileRefs.go
> +		fromDate, err := cmd.Flags().GetDuration("from_date")
Hmm, seems the from_date is not a date base on the code below where it is used. It is more like a last `N` days or minutes. The `date` may may confuse users, perhaps use `in`, so the command could be used like `recent-refs -in 3d` ? or use it as a date, so the code in line 56 below would not needed, but the date format should be defined.

2022-08-11 03:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/recent-refs  |
| gosdk  | feature/list-recent-files  |
| zboxcli  | feature/list-recent-files  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-08-15 02:13 UTC, peterlimg approved these changes
lgtm

2022-08-15 02:55 UTC, merged