throw non zero exit status on failure of copy and move command
0chain/zboxcli pull request #306
Opened 2022-09-30 15:38 UTC by boddumanohar

A brief description of the changes in this PR:

fixes https://github.com/0chain/zboxcli/issues/251

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

2022-10-12 13:33 UTC, cnlangzi requested changes

2022-10-12 13:33 UTC, cnlangzi commented on cmd/copy.go
>  			fmt.Println("Error fetching the allocation", err)
maybe it is better to use panic?
```suggestion
panic(""Error fetching the allocation: "+err.Error())
```

2022-10-12 13:51 UTC, boddumanohar commented
@cnlangzi  updated the PR as per comments. PTAL

2022-10-12 23:07 UTC, cnlangzi commented
> @cnlangzi updated the PR as per comments. PTAL

`os.Exit(1)` can be removed , because panic will throw 1 now

2022-10-14 01:11 UTC, cnlangzi approved these changes
LGTM

2022-10-17 07:24 UTC, cnlangzi approved these changes

2022-10-17 11:25 UTC, peterlimg approved these changes
lgtm

2022-10-17 22:13 UTC, cnlangzi commented
@boddumanohar please also fix related system_tests, thanks.

2022-10-27 23:00 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | file-copy  |
| gosdk  | staging  |
| zboxcli  | 251  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-01 11:41 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | file-copy  |
| gosdk  | staging  |
| zboxcli  | 251  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-01 12:52 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | 251  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-25 23:57 UTC, peterlimg commented
@boddumanohar please fix the system tests https://github.com/0chain/system_test/tree/file-copy.

2023-04-13 15:24 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | file-copy  |
| gosdk  | staging  |
| zboxcli  | 251  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-16 19:09 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | file-copy  |
| gosdk  | staging  |
| zboxcli  | 251  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-16 19:10 UTC, merged

2023-04-16 20:41 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | file-copy  |
| gosdk  | staging  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |