Fix/optimize handlers
0chain/zboxcli pull request #359
Opened 2023-02-20 18:19 UTC by dabasov

A brief description of the changes in this PR:

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

2023-02-20 19:10 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/optimize-handlers  |
| zwalletcli  | staging  |
| 0chain  | fix/optimize-handlers  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-22 04:56 UTC, peterlimg commented on cmd/stakepool.go
> +	spUserInfo.PersistentFlags().Int("offset", 0, "pass this option to get all the pools")
Let's correct the descriptions for `limit` and `offset`.

2023-02-22 04:57 UTC, peterlimg requested changes

2023-02-22 04:57 UTC, peterlimg commented on cmd/stakepool.go
> +	spUserInfo.PersistentFlags().Int("offset", 0, "pass this option to get all the pools")
Let's correct the descriptions for limit and offset.

2023-02-23 00:04 UTC, peterlimg approved these changes
LGTM

2023-02-23 16:44 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | true  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | fix/optimize-handlers  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-23 17:00 UTC, merged