Makin clientid and encryptionkey mandatory in encrypted share
0chain/zboxcli pull request #385
Opened 2023-03-12 14:21 UTC by SinanEkm

A brief description of the changes in this PR:

Related issue:  [zboxcli#357](https://github.com/0chain/zboxcli/issues/357)

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/zboxcli/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

Associated PRs (Link as appropriate):
- 0chain: 
- blobber:
- gosdk:
- system_test:
- zwalletcli:
- Other: ...

2023-03-13 19:49 UTC, Kishan-Dhakan requested changes

2023-03-13 19:49 UTC, Kishan-Dhakan commented on cmd/share.go
> +			PrintError("Clientid and/or encryptionpublickey are missing for the encrypted share!")
This is not ideal, please use persistent flags like how it is done in other commands. Look at other commands' code to see how persistent flags work.

2023-03-18 18:52 UTC, Kishan-Dhakan approved these changes

2023-03-21 20:51 UTC, Kishan-Dhakan requested changes
clientid should be checked in the if condition too

2023-03-21 21:01 UTC, SinanEkm commented
> clientid should be checked in the if condition too

I know that but I realized that clientid flag shouldn't be used if it is public share. I tried to use clientid flag by leaving it blank but it didn't work like that, I think clientid flag shouldn't use at all for public share. So, that's why I excluded clientid flag.

2023-03-21 22:11 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/TestShareFile  |
| gosdk  | staging  |
| zboxcli  | 357-for-encrypted-share-clientid-and-encryptionpublickey-should-be-mandatory  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-22 17:45 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | fix/TestShareFile  |
| gosdk  | staging  |
| zboxcli  | 357-for-encrypted-share-clientid-and-encryptionpublickey-should-be-mandatory  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-22 17:46 UTC, Kishan-Dhakan approved these changes

2023-03-22 17:47 UTC, merged