README.md changes
0chain/zboxcli pull request #519
Opened 2023-09-13 19:16 UTC by hm90121

--Correcting typos wherever possible
--Correcting index for table of contents
-- corrected live streaming section
-- added separate section for upload with webstream as stream
-- added how to unforbid

2023-09-22 18:18 UTC, Kishan-Dhakan requested changes

2023-09-22 18:18 UTC, Kishan-Dhakan commented on README.md
> +There are various operations which you can forbid on an allocation. Forbid flag works with [update allocation](#update-allocation) command. Check its working before proceeding.
Please remove `Check its working before proceeding`. In general, everything in the docs is expected to be checked by the doc team and should be left to readers to check.

2023-09-22 18:18 UTC, Kishan-Dhakan commented on README.md
> +To Unforbid an operation after forbiding:
Forbidding* (spelling)

2023-09-22 18:18 UTC, Kishan-Dhakan commented on README.md
> +`./zbox kill-blobber` command deactivates a blobber to avoid storage of data. Required parameters are :
Remove spacing before `:`

2023-09-26 10:44 UTC, hm90121 commented
added suggestions

2023-09-28 08:11 UTC, Kishan-Dhakan approved these changes

2023-09-28 08:11 UTC, merged