Call new remove-curator 0chain endpoint
0chain/zboxcli pull request #83
Opened 2021-08-10 17:02 UTC by Sriep

2021-08-14 02:00 UTC, cnlangzi requested changes

2021-08-14 13:44 UTC, Sriep commented on cmd/removecurator.go
> +		log.Print(curatorID + " removed " + curatorID + " as a curator to allocation " + allocationID)
Not sure, but I am just copying everyone else.

2021-08-14 13:44 UTC, Sriep commented on cmd/addcurator.go
> +		log.Print(curatorID + " added " + curatorID + " as a curator to allocation " + allocationID)
Not sure, but I am just copying everyone else. zbox is a straightforward `cobra` command-line application so there is no obvious reason to anything other than "log".

2021-08-15 01:50 UTC, cnlangzi commented on cmd/addcurator.go
> +		log.Print(curatorID + " added " + curatorID + " as a curator to allocation " + allocationID)
if so, please remove log.Print for debugging. It break `--silent` feature

2021-08-15 01:50 UTC, cnlangzi commented on cmd/removecurator.go
> +		log.Print(curatorID + " removed " + curatorID + " as a curator to allocation " + allocationID)
if so, please remove log.Print for debugging. It break `--silent` feature

2021-08-23 12:45 UTC, Sriep commented on cmd/addcurator.go
> +		log.Print(curatorID + " added " + curatorID + " as a curator to allocation " + allocationID)
I don't understand.
```
"silent", false, "Do not show interactive sdk logs (shown by default)"
```
The output from `log` is not part of the sdk logs.

2021-08-23 12:46 UTC, Sriep commented on cmd/removecurator.go
> +		log.Print(curatorID + " removed " + curatorID + " as a curator to allocation " + allocationID)
I don't understand.
```
"silent", false, "Do not show interactive sdk logs (shown by default)"
```
The output from `log` is not part of the sdk logs.

2021-08-24 01:43 UTC, cnlangzi approved these changes
LGTM

2021-08-24 10:13 UTC, merged